In [1]:
#importing Libraries
import pandas as pd 
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report, accuracy_score

In [2]:
import sys
print(sys.executable)

c:\Users\Gerar\AppData\Local\Programs\Python\Python311\python.exe

In [2]:
#loading data 
df_train = pd.read_csv("final_train_70.csv")

In [4]:
df_train.head()

,id,keyword,location,text,target,disaster_type
0,460,armageddon,Phuket,ARMAGEDDON LONDON | http://t.co/CULU2OwIUc,0,Not a disaster
1,7017,mayhem,NaN,RETWEET #FOLLOWnGAIN\n\n@TheMGWVboss \n\n??#FO...,0,Not a disaster
2,4139,drought,"Macon, Georgia",Moderate #drought is spreading rapidly across ...,1,Other disaster
3,7285,nuclear%20disaster,NaN,Fukushima: The Story of a Nuclear Disaster htt...,1,Other disaster
4,4998,explosion,"Long Island, NY",We found a sunflower explosion on our walk. ht...,1,Explosion

In [ ]:
df_train = df_train.drop(["keyword","location","target"],axis=1)

In [9]:
df_train.head()

     id                                               text   disaster_type
0   460       ARMAGEDDON LONDON  |  http://t.co/CULU2OwIUc  Not a disaster
1  7017  RETWEET #FOLLOWnGAIN\n\n@TheMGWVboss \n\n??#FO...  Not a disaster
2  4139  Moderate #drought is spreading rapidly across ...  Other disaster
3  7285  Fukushima: The Story of a Nuclear Disaster htt...  Other disaster
4  4998  We found a sunflower explosion on our walk. ht...       Explosion

In [10]:
df_train = df_train.rename(columns={"disaster_type":"category"})

In [11]:
df_train.head()

     id                                               text        category
0   460       ARMAGEDDON LONDON  |  http://t.co/CULU2OwIUc  Not a disaster
1  7017  RETWEET #FOLLOWnGAIN\n\n@TheMGWVboss \n\n??#FO...  Not a disaster
2  4139  Moderate #drought is spreading rapidly across ...  Other disaster
3  7285  Fukushima: The Story of a Nuclear Disaster htt...  Other disaster
4  4998  We found a sunflower explosion on our walk. ht...       Explosion

In [15]:
df_train["text"].head()

0                                                                                          ARMAGEDDON LONDON  |  http://t.co/CULU2OwIUc
1         RETWEET #FOLLOWnGAIN\n\n@TheMGWVboss \n\n??#FOLLOW?? ?~( ??~Û¢)~? @ynovak @IAmMrCash @Frankies_Style @MamanyaDana @Mayhem_4U
2    Moderate #drought is spreading rapidly across central Ga. #Macon #WarnerRobins #Dublin #Milledgeville #gawx http://t.co/PHNEZ60cwe
3                                              Fukushima: The Story of a Nuclear Disaster http://t.co/ikpnGs3dTi http://t.co/lJHgSdRAEZ
4                                             We found a sunflower explosion on our walk. http://t.co/vLNmkLWWby http://t.co/P769eo49Fj
Name: text, dtype: object

In [14]:
pd.set_option("display.max_colwidth",None)

In [17]:
df_train.to_csv("train_70.csv")

In [18]:
df_test = pd.read_csv("final_val_30.csv")

In [19]:
df_test = df_test.drop(["keyword","location","target"],axis=1)

In [22]:
df_test.head()

,id,text,category
0,11320,Emergency services are responding to flood damage in Berlin.,Flood
1,1639,The cryptic words that guided pilots on the Hiroshima bombing mission http://t.co/nSS5L64cvR #canada,Explosion
2,6363,@minhazmerchant Great job done by village hostages,Violence/Attack/Terrorism
3,10795,Israel wrecked my home. Now it wants my land. \nhttps://t.co/g0r3ZR1nQj,Accident/Crash
4,2947,Too dangerous for them. But it's OK for the rest of us to be in danger. https://t.co/YL67DKf4tb,Not a disaster

In [21]:
df_test = df_test.rename(columns={"disaster_type":"category"})

In [23]:
df_test.to_csv("test_30.csv")

In [25]:
mask = df_train["text"].str.startswith(("'",'"'))

In [26]:
mask.head()

0    False
1    False
2    False
3    False
4    False
Name: text, dtype: bool

In [27]:
mask

0       False
1       False
2       False
3       False
4       False
        ...
5724    False
5725    False
5726    False
5727    False
5728    False
Name: text, Length: 5729, dtype: bool

In [30]:
mask.head(100)

0     False
1     False
2     False
3     False
4     False
5     False
6      True
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30     True
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49    False
50    False
51    False
52    False
53    False
54    False
55    False
56    False
57    False
58    False
59    False
60    False
61    False
62    False
63    False
64    False
65    False
66    False
67    False
68    False
69    False
70    False
71    False
72    False
73    False
74    False
75     True
76    False
77    False
78    False
79    False
80    False
81    False
82    False
83    False
84    False
85    False
86    False
87    False
88    False
89    False
90    False
91    False
92    False
93    False
94    False
95    False
96    False
97    False
98    False
99    False
Name: text, dtype: bool

In [29]:
pd.set_option("display.max_rows", None)

In [31]:
df_train.loc[6, "text"]

"'There was a small earthquake in LA but don't worry Emily Rossum is fine' #difficultpeople is great"

In [33]:
df_train.loc[75, "text"]

"'The Latest: More Homes Razed by Northern California Wildfire' by THE ASSOCIATED PRESS via NYT http://t.co/rDF0ZuW7lZ"

In [34]:
mask.sum()

np.int64(84)

In [37]:
mask2 = df_train["text"].str.endswith(("'",'"'))

In [38]:
mask2.sum()

np.int64(52)

In [40]:
# 1. Identify rows with leading/trailing quotes
mask = df_train["text"].str.startswith(("'", '"')) | df_train["text"].str.endswith(("'", '"'))

# 2. Preview them
df_train.loc[mask, "text"].head()

# 3. Clean
df_train["text"] = df_train["text"].str.strip("'\"")

In [41]:
df_train.loc[mask, "text"].head()

6                                             There was a small earthquake in LA but don't worry Emily Rossum is fine' #difficultpeople is great
30                      Anyway' the old lady went on 'I have something to ask of you - and you alone.' THE COMING TSUNAMI http://t.co/tYeWZf3hqA
75                          The Latest: More Homes Razed by Northern California Wildfire' by THE ASSOCIATED PRESS via NYT http://t.co/rDF0ZuW7lZ
90     @AllOutAsh23_sN Heard you got obliterated and also that your brother/boyfriend ran out of the building crying last night. LOL. 'MD/VA!!!!
115                                                                                         Drowning' - Acrylic 08.05.15 https://t.co/X17fUBQBGG
Name: text, dtype: object

In [42]:
# 1. Identify rows with leading/trailing quotes
mask = df_test["text"].str.startswith(("'", '"')) | df_test["text"].str.endswith(("'", '"'))

# 2. Preview them
df_test.loc[mask, "text"].head()

# 3. Clean
df_test["text"] = df_test["text"].str.strip("'\"")

In [43]:
df_test.loc[mask, "text"].head()

23    Without an ally near you can't use this skill.' How did you get hired? Really cause it's making every Riot staff member look incompetent.
26                                                                                 Fatal crash reported on Johns Island' http://t.co/d2i9bL89Zo
28                    the third generation atomic bombed survivor' Photo exhibition 11:00 to 18:00 8/6. \n#?? #Hiroshima http://t.co/gVAipmLSl0
39                                             Biggest lead hazard in New England history.' Yeah let's nail these guys. https://t.co/xzvmzQuS0x
42                                         Calgarians stunned by storm insurance companies busy handling calls' #abstorm http://t.co/fkFa9vSssZ
Name: text, dtype: object

In [45]:
df_test.to_csv("test_30.csv")

In [46]:
df_train.to_csv("train_70.csv")

Making the test/ train

In [47]:
X_train = df_train["text"]
y_train = df_train["category"]

X_test = df_test["text"]
y_test = df_test["category"]

In [48]:
model= Pipeline([
    ("tfidf",TfidfVectorizer(
        max_features=15000,
        ngram_range= (1,2),
        min_df =3,
        stop_words="english"
    )),
    ("logreg",LogisticRegression(
        max_iter=1000,
        n_jobs=-1,
        multi_class="auto"
    ))
])

In [49]:
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print(classification_report(y_test, y_pred))

c:\Users\Gerar\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:1272: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.8. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(

                           precision    recall  f1-score   support

           Accident/Crash       0.97      0.65      0.78       109
               Earthquake       0.99      0.91      0.95       110
                Explosion       0.98      0.71      0.82       126
            Fire/Wildfire       0.96      0.56      0.71       169
                    Flood       0.95      0.84      0.89       100
           Not a disaster       0.62      0.87      0.73      1026
           Other disaster       0.58      0.37      0.45       521
  Storm/Hurricane/Tornado       0.93      0.74      0.82       168
Violence/Attack/Terrorism       0.97      0.67      0.79       126

                 accuracy                           0.71      2455
                macro avg       0.88      0.70      0.77      2455
             weighted avg       0.74      0.71      0.70      2455

In [50]:
model2= Pipeline([
    ("tfidf",TfidfVectorizer(
        max_features=15000,
        ngram_range= (1,2),
        min_df =3,
        stop_words="english"
    )),
    ("logreg",LogisticRegression(
        max_iter=1000,
        n_jobs=-1,
        multi_class="auto",
        class_weight="balanced"
    ))
])

In [66]:
model2.fit(X_train, y_train)
y_pred = model2.predict(X_test)
print(classification_report(y_test, y_pred))

c:\Users\Gerar\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:1272: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.8. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(

                           precision    recall  f1-score   support

           Accident/Crash       0.88      0.94      0.91       109
               Earthquake       0.96      0.98      0.97       110
                Explosion       0.93      0.92      0.92       126
            Fire/Wildfire       0.81      0.76      0.79       169
                    Flood       0.94      0.97      0.96       100
           Not a disaster       0.75      0.69      0.72      1026
           Other disaster       0.52      0.59      0.55       521
  Storm/Hurricane/Tornado       0.86      0.94      0.90       168
Violence/Attack/Terrorism       0.90      0.95      0.92       126

                 accuracy                           0.75      2455
                macro avg       0.84      0.86      0.85      2455
             weighted avg       0.75      0.75      0.75      2455

In [60]:
model3= Pipeline([
    ("tfidf",TfidfVectorizer(
        max_features=15000,
        ngram_range= (1,2),
        min_df =3,
    
    )),
    ("logreg",LogisticRegression(
        max_iter=1000,
        n_jobs=-1,
        multi_class="auto",
        class_weight="balanced"
    ))
])

In [65]:
model3.fit(X_train, y_train)
y_pred = model3.predict(X_test)
print(classification_report(y_test, y_pred))

c:\Users\Gerar\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:1272: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.8. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(

                           precision    recall  f1-score   support

           Accident/Crash       0.85      0.87      0.86       109
               Earthquake       0.96      0.97      0.97       110
                Explosion       0.94      0.90      0.92       126
            Fire/Wildfire       0.94      0.90      0.92       169
                    Flood       0.95      0.95      0.95       100
           Not a disaster       0.75      0.71      0.73      1026
           Other disaster       0.55      0.62      0.58       521
  Storm/Hurricane/Tornado       0.86      0.89      0.87       168
Violence/Attack/Terrorism       0.89      0.88      0.88       126

                 accuracy                           0.76      2455
                macro avg       0.85      0.85      0.85      2455
             weighted avg       0.77      0.76      0.76      2455

In [58]:
print(model3.get_params()["tfidf__stop_words"])

None

Best Logictic Regression Model is model4, not stopword removals and balanced class weights

In [62]:
model4= Pipeline([
    ("tfidf",TfidfVectorizer(
        max_features=15000,
        ngram_range= (1,2),
        min_df =2,
    
    )),
    ("logreg",LogisticRegression(
        max_iter=1000,
        n_jobs=-1,
        multi_class="auto",
        class_weight="balanced"
    ))
])

In [64]:
model4.fit(X_train, y_train)
y_pred = model4.predict(X_test)
print(classification_report(y_test, y_pred))

c:\Users\Gerar\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:1272: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.8. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(

                           precision    recall  f1-score   support

           Accident/Crash       0.84      0.88      0.86       109
               Earthquake       0.96      0.96      0.96       110
                Explosion       0.93      0.91      0.92       126
            Fire/Wildfire       0.94      0.91      0.92       169
                    Flood       0.96      0.94      0.95       100
           Not a disaster       0.74      0.70      0.72      1026
           Other disaster       0.54      0.60      0.57       521
  Storm/Hurricane/Tornado       0.85      0.89      0.87       168
Violence/Attack/Terrorism       0.91      0.88      0.90       126

                 accuracy                           0.76      2455
                macro avg       0.85      0.85      0.85      2455
             weighted avg       0.76      0.76      0.76      2455

In [84]:
tweets = [
    "Heavy flooding downtown, cars underwater.",
    "Did anyone hear that explosion?",
    "It's just a fire day."
]

model4.predict(tweets)

array(['Flood', 'Explosion', 'Fire/Wildfire'], dtype=object)

In [87]:
import pickle

with open("LogRegression_model.pkl", "wb") as f:
    pickle.dump(model4, f)

Using SVM

In [67]:
from sklearn.svm import LinearSVC
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer

model_svm = Pipeline([
    ("tfidf", TfidfVectorizer(
        max_features=15000,
        ngram_range=(1,2),
        min_df=2
    )),
    ("svm", LinearSVC())
])

model_svm.fit(X_train, y_train)
y_pred = model_svm.predict(X_test)
print(classification_report(y_test, y_pred))

                           precision    recall  f1-score   support

           Accident/Crash       0.92      0.77      0.84       109
               Earthquake       0.98      0.96      0.97       110
                Explosion       0.96      0.84      0.90       126
            Fire/Wildfire       0.95      0.87      0.91       169
                    Flood       0.95      0.96      0.96       100
           Not a disaster       0.68      0.80      0.73      1026
           Other disaster       0.55      0.44      0.49       521
  Storm/Hurricane/Tornado       0.87      0.85      0.86       168
Violence/Attack/Terrorism       0.95      0.80      0.87       126

                 accuracy                           0.74      2455
                macro avg       0.87      0.81      0.84      2455
             weighted avg       0.75      0.74      0.74      2455

In [68]:
from sklearn.svm import LinearSVC
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer

model_svm2 = Pipeline([
    ("tfidf", TfidfVectorizer(
        max_features=15000,
        ngram_range=(1,2),
        min_df=2
    )),
    ("svm", LinearSVC(class_weight="balanced"))
])

model_svm2.fit(X_train, y_train)
y_pred = model_svm2.predict(X_test)
print(classification_report(y_test, y_pred))

                           precision    recall  f1-score   support

           Accident/Crash       0.90      0.88      0.89       109
               Earthquake       0.97      0.97      0.97       110
                Explosion       0.95      0.92      0.94       126
            Fire/Wildfire       0.95      0.92      0.93       169
                    Flood       0.95      0.97      0.96       100
           Not a disaster       0.72      0.74      0.73      1026
           Other disaster       0.54      0.50      0.52       521
  Storm/Hurricane/Tornado       0.84      0.90      0.87       168
Violence/Attack/Terrorism       0.92      0.88      0.90       126

                 accuracy                           0.76      2455
                macro avg       0.86      0.85      0.86      2455
             weighted avg       0.75      0.76      0.76      2455

In [69]:
for C in [0.5, 1.0, 2.0]:
    print("\n=== C =", C, "===\n")
    model_tmp = Pipeline([
        ("tfidf", TfidfVectorizer(
            max_features=15000,
            ngram_range=(1, 2),
            min_df=2
        )),
        ("svm", LinearSVC(class_weight="balanced", C=C))
    ])

    model_tmp.fit(X_train, y_train)
    y_pred = model_tmp.predict(X_test)
    print(classification_report(y_test, y_pred))

=== C = 0.5 ===

                           precision    recall  f1-score   support

           Accident/Crash       0.89      0.90      0.89       109
               Earthquake       0.96      0.98      0.97       110
                Explosion       0.93      0.92      0.92       126
            Fire/Wildfire       0.95      0.92      0.93       169
                    Flood       0.95      0.97      0.96       100
           Not a disaster       0.73      0.76      0.74      1026
           Other disaster       0.57      0.51      0.53       521
  Storm/Hurricane/Tornado       0.84      0.90      0.87       168
Violence/Attack/Terrorism       0.90      0.89      0.89       126

                 accuracy                           0.77      2455
                macro avg       0.86      0.86      0.86      2455
             weighted avg       0.76      0.77      0.76      2455


=== C = 1.0 ===

                           precision    recall  f1-score   support

           Accident/Crash       0.90      0.88      0.89       109
               Earthquake       0.97      0.97      0.97       110
                Explosion       0.95      0.92      0.94       126
            Fire/Wildfire       0.95      0.92      0.93       169
                    Flood       0.95      0.97      0.96       100
           Not a disaster       0.72      0.74      0.73      1026
           Other disaster       0.54      0.50      0.52       521
  Storm/Hurricane/Tornado       0.84      0.90      0.87       168
Violence/Attack/Terrorism       0.92      0.88      0.90       126

                 accuracy                           0.76      2455
                macro avg       0.86      0.85      0.86      2455
             weighted avg       0.75      0.76      0.76      2455


=== C = 2.0 ===

                           precision    recall  f1-score   support

           Accident/Crash       0.90      0.87      0.89       109
               Earthquake       0.97      0.97      0.97       110
                Explosion       0.95      0.91      0.93       126
            Fire/Wildfire       0.94      0.92      0.93       169
                    Flood       0.94      0.98      0.96       100
           Not a disaster       0.71      0.74      0.72      1026
           Other disaster       0.53      0.50      0.51       521
  Storm/Hurricane/Tornado       0.84      0.90      0.87       168
Violence/Attack/Terrorism       0.92      0.84      0.88       126

                 accuracy                           0.75      2455
                macro avg       0.86      0.85      0.85      2455
             weighted avg       0.75      0.75      0.75      2455

Best Model is the SVC with C=0.5, 15000 max fatures, min_df =2

In [86]:
model_svc = Pipeline([
        ("tfidf", TfidfVectorizer(
            max_features=15000,
            ngram_range=(1, 2),
            min_df=2
        )),
        ("svm", LinearSVC(class_weight="balanced", C=0.5))
    ])

model_svc.fit(X_train, y_train)
y_pred = model_svc.predict(X_test)
print(classification_report(y_test, y_pred))

                           precision    recall  f1-score   support

           Accident/Crash       0.89      0.90      0.89       109
               Earthquake       0.96      0.98      0.97       110
                Explosion       0.93      0.92      0.92       126
            Fire/Wildfire       0.95      0.92      0.93       169
                    Flood       0.95      0.97      0.96       100
           Not a disaster       0.73      0.76      0.74      1026
           Other disaster       0.57      0.51      0.53       521
  Storm/Hurricane/Tornado       0.84      0.90      0.87       168
Violence/Attack/Terrorism       0.90      0.89      0.89       126

                 accuracy                           0.77      2455
                macro avg       0.86      0.86      0.86      2455
             weighted avg       0.76      0.77      0.76      2455

In [88]:
with open("SVC_model.pkl", "wb") as f:
    pickle.dump(model_svc, f)